/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Controlador;
import javax.swing.JOptionPane;
import view.ADMINISTRADOR.ADMINISTRADOR_PRINCIPAL;
import view.EMPLEADO.PRINCIPAL_EMPLEADO;

/**
 *
 * @author hdani
 */
public class Formulario_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Formulario_Principal
     */
    Controlador CONTROL;
    public Formulario_Principal() {
        initComponents();
        this.setSize(455, 630);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rSLabelImage2 = new necesario.RSLabelImage();
        password = new RSMaterialComponent.RSTextFieldTwo();
        user = new RSMaterialComponent.RSTextFieldTwo();
        rSLabelImage3 = new necesario.RSLabelImage();
        rSButtonRound1 = new rojerusan.RSButtonRound();
        rSLabelImage1 = new rojeru_san.rslabel.RSLabelImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(55, 65, 64));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSLabelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/istockphoto-936681148-612x612.jpg"))); // NOI18N
        jPanel1.add(rSLabelImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 60, 60));

        password.setForeground(new java.awt.Color(55, 65, 64));
        password.setBorderColor(new java.awt.Color(255, 153, 0));
        password.setPlaceholder("INGRESE SU CONTRASEÑA");
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, -1, -1));

        user.setForeground(new java.awt.Color(55, 65, 64));
        user.setBorderColor(new java.awt.Color(255, 153, 0));
        user.setPlaceholder("INGRESE USUARIO");
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));

        rSLabelImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título-1.jpg"))); // NOI18N
        jPanel1.add(rSLabelImage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 60, 60));

        rSButtonRound1.setBackground(new java.awt.Color(255, 153, 51));
        rSButtonRound1.setText("ACEPTAR");
        rSButtonRound1.setColorHover(new java.awt.Color(255, 102, 51));
        rSButtonRound1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, -1, -1));

        rSLabelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/depositphotos_110113468-stock-illustration-user-access-icon-user-access.jpg"))); // NOI18N
        jPanel1.add(rSLabelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 340, 350));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonRound1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound1ActionPerformed
        CONTROL = new Controlador();
        if(CONTROL.InicioDeSesion(user.getText(), password.getText())==0)
        {
            JOptionPane.showMessageDialog(null, "EL USUARIO INGRESADO ES INEXISTENTE","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        if(CONTROL.InicioDeSesion(user.getText(), password.getText())==1)
        {
            this.setVisible(false);
            ADMINISTRADOR_PRINCIPAL x=new ADMINISTRADOR_PRINCIPAL();
            x.setExtendedState(6);
            x.setVisible(true);
        }
        if(CONTROL.InicioDeSesion(user.getText(), password.getText())==2)
        {
            this.setVisible(false);
            PRINCIPAL_EMPLEADO x=new PRINCIPAL_EMPLEADO(user.getText(),password.getText());
            x.setExtendedState(6);
            x.setVisible(true);
        }
    }//GEN-LAST:event_rSButtonRound1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private RSMaterialComponent.RSTextFieldTwo password;
    private rojerusan.RSButtonRound rSButtonRound1;
    private rojeru_san.rslabel.RSLabelImage rSLabelImage1;
    private necesario.RSLabelImage rSLabelImage2;
    private necesario.RSLabelImage rSLabelImage3;
    private RSMaterialComponent.RSTextFieldTwo user;
    // End of variables declaration//GEN-END:variables
}
