/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.ADMINISTRADOR;

import controller.ControllerUser;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author hdani
 */
public class AÑADIR_USUARIO extends javax.swing.JInternalFrame {

    /**
     * Creates new form AÑADIR_EMPLEADO
     */
    JDesktopPane ini=null;
    JTable usu=null;
    private int bandera=0;
    public AÑADIR_USUARIO(JDesktopPane x, JTable us) {
        initComponents();
        ini=x;
        usu=us;
    }
    public AÑADIR_USUARIO(JDesktopPane x, JTable us,String CI,String Nombre,String Apellido, String Celular, String Usuario,String Contraseña, String Tipo) {
        initComponents();
        ini=x;
        usu=us;
        rSLabelTextIcon1.setText("EDITAR USUARIO");
        rSMTextFull1.setText(CI);
        rSMTextFull1.setEditable(false);
        rSMTextFull2.setText(Nombre);
        rSMTextFull3.setText(Apellido);
        rSMTextFull4.setText(Celular);
        rSMTextFull5.setText(Usuario);
        rSMTextFull6.setText(Contraseña);
        if(Tipo.equals("ADMINISTRADOR"))
        {
            rSComboBox1.setSelectedIndex(0);
        }
        else
        {
            rSComboBox1.setSelectedIndex(1);
        }
        rSButtonShade1.setText("ACTUALIZAR");
        bandera=100;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSMTextFull1 = new rojeru_san.RSMTextFull();
        rSMTextFull2 = new rojeru_san.RSMTextFull();
        rSMTextFull3 = new rojeru_san.RSMTextFull();
        rSMTextFull4 = new rojeru_san.RSMTextFull();
        rSMTextFull5 = new rojeru_san.RSMTextFull();
        rSMTextFull6 = new rojeru_san.RSMTextFull();
        rSButtonShade1 = new rscomponentshade.RSButtonShade();
        rSComboBox1 = new RSMaterialComponent.RSComboBox();
        rSLabelTextIcon1 = new RSMaterialComponent.RSLabelTextIcon();
        rSLabelTextIcon2 = new RSMaterialComponent.RSLabelTextIcon();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        rSMTextFull1.setPlaceholder("INSERTA EL CI");

        rSMTextFull2.setPlaceholder("INSERTA EL NOMBRE");

        rSMTextFull3.setPlaceholder("INSERTA EL APELLIDO");

        rSMTextFull4.setPlaceholder("INSERTA EL CELULAR");

        rSMTextFull5.setPlaceholder("INSERTA EL USUARIO");

        rSMTextFull6.setPlaceholder("INSERTA LA CONTRASEÑA");

        rSButtonShade1.setText("REGISTRAR");
        rSButtonShade1.setBgShadeHover(new java.awt.Color(0, 204, 255));
        rSButtonShade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonShade1ActionPerformed(evt);
            }
        });

        rSComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ADMINISTRADOR", "EMPLEADO" }));

        rSLabelTextIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ICONS_MANAGEMENT/22ed2b8524101426e7b490c95097a8f2-icono-de-ventas-comerciales.png"))); // NOI18N
        rSLabelTextIcon1.setText("INSERTAR USUARIO");
        rSLabelTextIcon1.setIconTextGap(10);
        rSLabelTextIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.INSERT_CHART);

        rSLabelTextIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ICONS_MANAGEMENT/22ed2b8524101426e7b490c95097a8f2-icono-de-ventas-comerciales.png"))); // NOI18N
        rSLabelTextIcon2.setText("SELECCIONA EL TIPO");
        rSLabelTextIcon2.setIconTextGap(10);
        rSLabelTextIcon2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.INSERT_EMOTICON);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 114, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rSComboBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rSMTextFull6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rSMTextFull5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rSMTextFull4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rSMTextFull1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rSMTextFull2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rSMTextFull3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rSLabelTextIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(rSButtonShade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSMTextFull1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSMTextFull2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSMTextFull3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSMTextFull4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSMTextFull5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSMTextFull6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSLabelTextIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rSComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(rSButtonShade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonShade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonShade1ActionPerformed
     
        if(bandera==0)
        {
            int dato=-1;
            ControllerUser Usuario=new ControllerUser();
            dato=Usuario.INSERTAR(rSMTextFull1.getText(),rSMTextFull2.getText(),rSMTextFull3.getText(),rSMTextFull4.getText(),rSMTextFull5.getText(),rSMTextFull6.getText(),rSComboBox1.getSelectedIndex()+1);
            switch (dato)
            {
                case -1:
                    JOptionPane.showMessageDialog(null, "Ocurrio un error","ERROR",JOptionPane.ERROR_MESSAGE);
                    break;
                case 0:
                    JOptionPane.showMessageDialog(null, "LA CUENTA DE USUARIO YA EXISTE","ERROR",JOptionPane.ERROR_MESSAGE);
                    break;
                case 1:
                    JOptionPane.showMessageDialog(null, "EL USUARIO YA EXISTE, ES ADMINISTRADOR","ERROR",JOptionPane.ERROR_MESSAGE);
                    break;
                case 2:
                    JOptionPane.showMessageDialog(null, "EL USUARIO YA EXISTE, ES EMPLEADO","ERROR",JOptionPane.ERROR_MESSAGE);
                    break;
                case 3:
                    JOptionPane.showMessageDialog(null, "EL USUARIO SE REGISTRO CON EXITO","ACEPTADO",JOptionPane.INFORMATION_MESSAGE);
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Ocurrio un error","ERROR",JOptionPane.ERROR);
            }
            usu.setModel(Usuario.MOSTRAR());
        }
        else
        {
            int dato=-1;
            ControllerUser Usuario=new ControllerUser();
            dato=Usuario.MODIFICAR(rSMTextFull1.getText(),rSMTextFull2.getText(),rSMTextFull3.getText(),rSMTextFull4.getText(),rSMTextFull5.getText(),rSMTextFull6.getText(),rSComboBox1.getSelectedIndex()+1);
            switch (dato)
            {
                case -1:
                    JOptionPane.showMessageDialog(null, "Ocurrio un error","ERROR",JOptionPane.ERROR);
                    break;
                case 0:
                    JOptionPane.showMessageDialog(null, "NO ES POSIBLE ACTUALIZAR EL DATO DEBE SER ELIMINADO","ERROR",JOptionPane.ERROR);
                    break;
                case 1:
                    JOptionPane.showMessageDialog(null, "EL USUARIO SE EDITO CON EXITO","ACEPTADO",JOptionPane.INFORMATION_MESSAGE);
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Ocurrio un error","ERROR",JOptionPane.ERROR);
            }
            usu.setModel(Usuario.MOSTRAR());
        }
        ini.repaint();
        ini.revalidate();
    }//GEN-LAST:event_rSButtonShade1ActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        ini.repaint();
        ini.revalidate();        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rscomponentshade.RSButtonShade rSButtonShade1;
    private RSMaterialComponent.RSComboBox rSComboBox1;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon1;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon2;
    private rojeru_san.RSMTextFull rSMTextFull1;
    private rojeru_san.RSMTextFull rSMTextFull2;
    private rojeru_san.RSMTextFull rSMTextFull3;
    private rojeru_san.RSMTextFull rSMTextFull4;
    private rojeru_san.RSMTextFull rSMTextFull5;
    private rojeru_san.RSMTextFull rSMTextFull6;
    // End of variables declaration//GEN-END:variables
}
