/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.ADMINISTRADOR;

import controller.ControllerProducto;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author hdani
 */
public class AÑADIR_PRODUCTO extends javax.swing.JInternalFrame {

    /**
     * Creates new form AÑADIR_PRODUCTO
     */
    public JTable tabla=null;
    public JDesktopPane panel=null;
    public int bandera=-1;
    public int fila=0;
    public AÑADIR_PRODUCTO(JTable tabla, JDesktopPane panel,int bandera) {
        initComponents();
        this.panel=panel;
        this.tabla=tabla;
        this.bandera=bandera;
    }
    public AÑADIR_PRODUCTO(JTable tabla, JDesktopPane panel,int bandera,int fila) {
        initComponents();
        this.panel=panel;
        this.tabla=tabla;
        this.bandera=bandera;
        this.fila=fila;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSLabelTextIcon1 = new RSMaterialComponent.RSLabelTextIcon();
        rSMTextFull1 = new rojeru_san.RSMTextFull();
        rSMTextFull2 = new rojeru_san.RSMTextFull();
        rSMTextFull3 = new rojeru_san.RSMTextFull();
        rSMTextFull4 = new rojeru_san.RSMTextFull();
        rSMTextFull5 = new rojeru_san.RSMTextFull();
        rSButtonShade3 = new rscomponentshade.RSButtonShade();
        rSMTextFull6 = new rojeru_san.RSMTextFull();
        rSMTextFull7 = new rojeru_san.RSMTextFull();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        rSLabelTextIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ICONS_MANAGEMENT/22ed2b8524101426e7b490c95097a8f2-icono-de-ventas-comerciales.png"))); // NOI18N
        rSLabelTextIcon1.setText("INSERTAR PRODUCTO");
        rSLabelTextIcon1.setIconTextGap(10);
        rSLabelTextIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.INSERT_CHART);

        rSMTextFull1.setPlaceholder("INSERTA EL CODIGO DEL PRODUCTO");

        rSMTextFull2.setPlaceholder("INSERTA LA DESCRIPCION DEL PRODUCTO");

        rSMTextFull3.setPlaceholder("INSERTA LA MARCA DEL PRODCUTO");

        rSMTextFull4.setPlaceholder("INSERTA EL PRECIO DEL PRODUCTO");

        rSMTextFull5.setPlaceholder("INSERTA LA CANTIDAD");

        rSButtonShade3.setText("REGISTRAR");
        rSButtonShade3.setBgShadeHover(new java.awt.Color(0, 204, 255));
        rSButtonShade3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonShade3ActionPerformed(evt);
            }
        });

        rSMTextFull6.setPlaceholder("INSERTA EL ROVEEDOR");

        rSMTextFull7.setPlaceholder("INSERTA EL PRECIO DE VENTA DEL PRODUCTO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 160, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rSMTextFull1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rSMTextFull5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rSMTextFull4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rSMTextFull2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rSMTextFull3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rSMTextFull6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rSMTextFull7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(46, 46, 46))))
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(rSButtonShade3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSMTextFull1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(rSMTextFull2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSMTextFull3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSMTextFull4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSMTextFull7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSMTextFull5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSMTextFull6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(rSButtonShade3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonShade3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonShade3ActionPerformed

        if(bandera==0)
        {
            int datos=-1;
            ControllerProducto Producto=new ControllerProducto();
            datos=Producto.INSERTAR(rSMTextFull1.getText(),rSMTextFull2.getText(),rSMTextFull3.getText(),rSMTextFull4.getText().replace(",", "."),rSMTextFull7.getText().replace(",", "."),rSMTextFull5.getText(),rSMTextFull6.getText());
            switch (datos)
            {
                case -1:
                    JOptionPane.showMessageDialog(null, "Ocurrio un error el producto ya existe, recargue la tabla","ERROR",JOptionPane.ERROR);
                    break;
                case 0:
                    JOptionPane.showMessageDialog(null, "Ocurrio un error el producto ya existe, recargue la tabla","ERROR",JOptionPane.ERROR);
                    break;
                case 1:
                    JOptionPane.showMessageDialog(null, "INSERTADO CON EXITO","CORRECTO",JOptionPane.INFORMATION_MESSAGE);
                    break;
            }
            Producto.Mostrar(tabla);
            panel.repaint();
            panel.revalidate();
        }
        else
        {
           
            int dato=-1;
            ControllerProducto Productos=new ControllerProducto();
            dato=Productos.MODIFICAR(rSMTextFull1.getText(),rSMTextFull2.getText(),rSMTextFull3.getText(),rSMTextFull4.getText().replace(",", "."),rSMTextFull7.getText().replace(",", "."),rSMTextFull5.getText(),rSMTextFull6.getText());
            switch (dato)
            {
                case -1:
                    JOptionPane.showMessageDialog(null, "Ocurrio un error, recargue la tabla","ERROR",JOptionPane.ERROR);
                    break;
                case 0:
                    JOptionPane.showMessageDialog(null, "Ocurrio un error, recargue la tabla","ERROR",JOptionPane.ERROR);
                    break;
                case 1:
                    JOptionPane.showMessageDialog(null, "EDITADO CON EXITO","CORRECTO",JOptionPane.INFORMATION_MESSAGE);
                    break;
            }
            Productos.Mostrar(tabla);
            panel.repaint();
            panel.revalidate();
        }
    }//GEN-LAST:event_rSButtonShade3ActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        if(bandera==1){
            rSLabelTextIcon1.setText("EDITAR PRODUCTO");
            rSButtonShade3.setText("EDITAR");
            rSMTextFull1.setText(tabla.getModel().getValueAt(fila, 0).toString());
            rSMTextFull1.setEditable(false);
            rSMTextFull2.setText(tabla.getModel().getValueAt(fila, 1).toString());
            rSMTextFull3.setText(tabla.getModel().getValueAt(fila, 2).toString());
            rSMTextFull4.setText(tabla.getModel().getValueAt(fila, 3).toString());
            rSMTextFull5.setText(tabla.getModel().getValueAt(fila, 4).toString());
            rSMTextFull6.setText(tabla.getModel().getValueAt(fila, 5).toString());
        }
    }//GEN-LAST:event_formInternalFrameActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rscomponentshade.RSButtonShade rSButtonShade3;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon1;
    private rojeru_san.RSMTextFull rSMTextFull1;
    private rojeru_san.RSMTextFull rSMTextFull2;
    private rojeru_san.RSMTextFull rSMTextFull3;
    private rojeru_san.RSMTextFull rSMTextFull4;
    private rojeru_san.RSMTextFull rSMTextFull5;
    private rojeru_san.RSMTextFull rSMTextFull6;
    private rojeru_san.RSMTextFull rSMTextFull7;
    // End of variables declaration//GEN-END:variables
}
