/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.ADMINISTRADOR;

import controller.ControllerUser;
import java.awt.Color;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author hdani
 */
public class USUARIO extends javax.swing.JInternalFrame {

    /**
     * Creates new form EMPLEADOS
     */
    JDesktopPane ini;
    public USUARIO(JDesktopPane x) {
        initComponents();
        ini=x;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rSButtonPane1 = new rojerusan.RSButtonPane();
        rSPanelImage1 = new rojeru_san.rspanel.RSPanelImage();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new RSMaterialComponent.RSTableMetro();
        rSButtonPane2 = new rojerusan.RSButtonPane();
        rSPanelImage2 = new rojeru_san.rspanel.RSPanelImage();
        jLabel2 = new javax.swing.JLabel();
        rSButtonPane3 = new rojerusan.RSButtonPane();
        rSPanelImage3 = new rojeru_san.rspanel.RSPanelImage();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setResizable(true);
        setTitle("EMPLEADOS");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        rSButtonPane1.setBackground(new java.awt.Color(0, 153, 204));
        rSButtonPane1.setColorHover(java.awt.Color.orange);
        rSButtonPane1.setOpaque(false);
        rSButtonPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonPane1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rSButtonPane1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rSButtonPane1MouseExited(evt);
            }
        });

        rSPanelImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ICONS_MANAGEMENT/Sin título-1.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage1Layout = new javax.swing.GroupLayout(rSPanelImage1);
        rSPanelImage1.setLayout(rSPanelImage1Layout);
        rSPanelImage1Layout.setHorizontalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );
        rSPanelImage1Layout.setVerticalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AÑADIR USUARIO");

        javax.swing.GroupLayout rSButtonPane1Layout = new javax.swing.GroupLayout(rSButtonPane1);
        rSButtonPane1.setLayout(rSButtonPane1Layout);
        rSButtonPane1Layout.setHorizontalGroup(
            rSButtonPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSButtonPane1Layout.createSequentialGroup()
                .addGroup(rSButtonPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rSButtonPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rSButtonPane1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(rSPanelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rSButtonPane1Layout.setVerticalGroup(
            rSButtonPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSButtonPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSPanelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla);

        rSButtonPane2.setBackground(new java.awt.Color(0, 153, 204));
        rSButtonPane2.setColorHover(java.awt.Color.orange);
        rSButtonPane2.setOpaque(false);
        rSButtonPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonPane2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rSButtonPane2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rSButtonPane2MouseExited(evt);
            }
        });

        rSPanelImage2.setImagen(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ICONS_MANAGEMENT/CERRAR.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage2Layout = new javax.swing.GroupLayout(rSPanelImage2);
        rSPanelImage2.setLayout(rSPanelImage2Layout);
        rSPanelImage2Layout.setHorizontalGroup(
            rSPanelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 104, Short.MAX_VALUE)
        );
        rSPanelImage2Layout.setVerticalGroup(
            rSPanelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ELIMINAR USUARIO");

        javax.swing.GroupLayout rSButtonPane2Layout = new javax.swing.GroupLayout(rSButtonPane2);
        rSButtonPane2.setLayout(rSButtonPane2Layout);
        rSButtonPane2Layout.setHorizontalGroup(
            rSButtonPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSButtonPane2Layout.createSequentialGroup()
                .addGroup(rSButtonPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rSButtonPane2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rSButtonPane2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(rSPanelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rSButtonPane2Layout.setVerticalGroup(
            rSButtonPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSButtonPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSPanelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rSButtonPane3.setBackground(new java.awt.Color(0, 153, 204));
        rSButtonPane3.setColorHover(java.awt.Color.orange);
        rSButtonPane3.setOpaque(false);
        rSButtonPane3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonPane3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rSButtonPane3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rSButtonPane3MouseExited(evt);
            }
        });

        rSPanelImage3.setImagen(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ICONS_MANAGEMENT/Sin título-11.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage3Layout = new javax.swing.GroupLayout(rSPanelImage3);
        rSPanelImage3.setLayout(rSPanelImage3Layout);
        rSPanelImage3Layout.setHorizontalGroup(
            rSPanelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 104, Short.MAX_VALUE)
        );
        rSPanelImage3Layout.setVerticalGroup(
            rSPanelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("EDITAR USUARIO");

        javax.swing.GroupLayout rSButtonPane3Layout = new javax.swing.GroupLayout(rSButtonPane3);
        rSButtonPane3.setLayout(rSButtonPane3Layout);
        rSButtonPane3Layout.setHorizontalGroup(
            rSButtonPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSButtonPane3Layout.createSequentialGroup()
                .addGroup(rSButtonPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rSButtonPane3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rSButtonPane3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(rSPanelImage3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rSButtonPane3Layout.setVerticalGroup(
            rSButtonPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSButtonPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSPanelImage3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1262, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(rSButtonPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSButtonPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(295, 295, 295)
                .addComponent(rSButtonPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(rSButtonPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(rSButtonPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(rSButtonPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonPane1MouseClicked
        AÑADIR_USUARIO ad=new AÑADIR_USUARIO(ini,this.tabla);
        ini.add(ad);
        ad.setLocation(10, 10);
        ad.setVisible(true);
        ini.repaint();
        ini.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonPane1MouseClicked

    private void rSButtonPane1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonPane1MouseEntered
        rSButtonPane1.setOpaque(true);
        rSButtonPane1.setColorHover(Color.orange);
        jLabel1.setForeground(Color.DARK_GRAY);
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonPane1MouseEntered

    private void rSButtonPane1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonPane1MouseExited
        rSButtonPane1.setOpaque(false);
        jLabel1.setForeground(Color.WHITE);
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonPane1MouseExited

    private void rSButtonPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonPane2MouseClicked
        ControllerUser user=new ControllerUser();
        int dato=user.BORRAR(tabla.getModel().getValueAt(tabla.getSelectedRow(),0 ).toString());
        
        switch (dato) {
            case -1:
                JOptionPane.showMessageDialog(null, "SOLO PUEDE MODIFICAR","INFORMACION",JOptionPane.WARNING_MESSAGE);
                break;
            case 0:
                JOptionPane.showMessageDialog(null, "SOLO PUEDE MODIFICAR","INFORMACION",JOptionPane.WARNING_MESSAGE);
                break;
            case 1:
                JOptionPane.showMessageDialog(null, "EL USUARIO SE ELIMINO CORRECTAMENTE","CORRECTO",JOptionPane.INFORMATION_MESSAGE);
                break;
            default:
                throw new AssertionError();
        }
        tabla.setModel(user.MOSTRAR());
        ini.repaint();
        ini.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonPane2MouseClicked

    private void rSButtonPane2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonPane2MouseEntered
        rSButtonPane2.setOpaque(true);
        rSButtonPane2.setColorHover(Color.orange);
        jLabel2.setForeground(Color.DARK_GRAY);// TODO add your handling code here:
    }//GEN-LAST:event_rSButtonPane2MouseEntered

    private void rSButtonPane2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonPane2MouseExited
        rSButtonPane2.setOpaque(false);
        jLabel2.setForeground(Color.WHITE);// TODO add your handling code here:
    }//GEN-LAST:event_rSButtonPane2MouseExited

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        ControllerUser usuario=new ControllerUser();
        tabla.setModel(usuario.MOSTRAR());
        tabla.setRowSelectionInterval(0, 0);
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameOpened

    private void rSButtonPane3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonPane3MouseClicked
        AÑADIR_USUARIO user=new AÑADIR_USUARIO(ini, tabla,tabla.getModel().getValueAt(tabla.getSelectedRow(),0 ).toString() , tabla.getModel().getValueAt(tabla.getSelectedRow(),1 ).toString(), tabla.getModel().getValueAt(tabla.getSelectedRow(),2 ).toString(), tabla.getModel().getValueAt(tabla.getSelectedRow(),3 ).toString(), tabla.getModel().getValueAt(tabla.getSelectedRow(),5 ).toString(), tabla.getModel().getValueAt(tabla.getSelectedRow(),6 ).toString(), tabla.getModel().getValueAt(tabla.getSelectedRow(),4 ).toString());
        ini.add(user);
        user.setLocation(10, 10);
        user.setVisible(true);
        ini.repaint();
        ini.revalidate();
// TODO add your handling code here:
    }//GEN-LAST:event_rSButtonPane3MouseClicked

    private void rSButtonPane3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonPane3MouseEntered
        rSButtonPane3.setOpaque(true);
        rSButtonPane3.setColorHover(Color.orange);
        jLabel3.setForeground(Color.DARK_GRAY);
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonPane3MouseEntered

    private void rSButtonPane3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonPane3MouseExited
        rSButtonPane3.setOpaque(false);
        jLabel3.setForeground(Color.WHITE);
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonPane3MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private rojerusan.RSButtonPane rSButtonPane1;
    private rojerusan.RSButtonPane rSButtonPane2;
    private rojerusan.RSButtonPane rSButtonPane3;
    private rojeru_san.rspanel.RSPanelImage rSPanelImage1;
    private rojeru_san.rspanel.RSPanelImage rSPanelImage2;
    private rojeru_san.rspanel.RSPanelImage rSPanelImage3;
    public RSMaterialComponent.RSTableMetro tabla;
    // End of variables declaration//GEN-END:variables
}
