/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.EMPLEADO;

import controller.ControllerCliente;
import controller.ControllerProducto;
import controller.ControllerVentas;
import java.math.BigDecimal;
import java.math.RoundingMode;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author hdani
 */
public class REALIZAR_VENTA extends javax.swing.JInternalFrame {

    /**
     * Creates new form REALIZAR_VENTA
     */
    JDesktopPane panel=null;
    public String usuario="",contrasena="";
    JTable tabla=null;
    public REALIZAR_VENTA(JDesktopPane panel,String us, String con,JTable tabla) {
        initComponents();
        this.panel=panel;
        this.usuario=us;
        this.contrasena=con;
        this.tabla=tabla;
        TableColumnModel columnModel = rSTableMetro11.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(200);
        columnModel.getColumn(1).setPreferredWidth(500);
        columnModel.getColumn(2).setPreferredWidth(100);
        columnModel.getColumn(3).setPreferredWidth(100);
        columnModel.getColumn(4).setPreferredWidth(100);
        columnModel.getColumn(5).setPreferredWidth(100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSTextFieldIconDos1 = new RSMaterialComponent.RSTextFieldIconDos();
        rSTextFieldIconDos2 = new RSMaterialComponent.RSTextFieldIconDos();
        rSTextFieldIconDos3 = new RSMaterialComponent.RSTextFieldIconDos();
        rSTextFieldIconDos4 = new RSMaterialComponent.RSTextFieldIconDos();
        rSTextFieldIconDos5 = new RSMaterialComponent.RSTextFieldIconDos();
        rSTextFieldIconDos6 = new RSMaterialComponent.RSTextFieldIconDos();
        rSTextFieldIconDos7 = new RSMaterialComponent.RSTextFieldIconDos();
        rSButton1 = new rojeru_san.RSButton();
        rSLabelBorderRound1 = new rojeru_san.rslabel.RSLabelBorderRound();
        rSLabelTextIcon1 = new RSMaterialComponent.RSLabelTextIcon();
        jScrollPane1 = new javax.swing.JScrollPane();
        rSTableMetro11 = new rojerusan.RSTableMetro1();
        rSButton2 = new rojeru_san.RSButton();
        rSLabelTextIcon2 = new RSMaterialComponent.RSLabelTextIcon();
        rSLabelBorderRound2 = new rojeru_san.rslabel.RSLabelBorderRound();
        rSButton3 = new rojeru_san.RSButton();
        rSTextFieldIconDos8 = new RSMaterialComponent.RSTextFieldIconDos();
        rSTextFieldIconDos9 = new RSMaterialComponent.RSTextFieldIconDos();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setResizable(true);
        setTitle("REALIZAR VENTA");

        rSTextFieldIconDos1.setForeground(new java.awt.Color(0, 153, 51));
        rSTextFieldIconDos1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PEOPLE);
        rSTextFieldIconDos1.setPlaceholder("INGRESA EL CI DEL CLIENTE");
        rSTextFieldIconDos1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rSTextFieldIconDos1KeyReleased(evt);
            }
        });

        rSTextFieldIconDos2.setForeground(new java.awt.Color(0, 153, 51));
        rSTextFieldIconDos2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PEOPLE);
        rSTextFieldIconDos2.setPlaceholder("INGRESA EL NOMBRE DEL CLIENTE");

        rSTextFieldIconDos3.setForeground(new java.awt.Color(0, 153, 51));
        rSTextFieldIconDos3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PEOPLE);
        rSTextFieldIconDos3.setPlaceholder("INGRESA EL APELLIDO DEL CLIENTE");

        rSTextFieldIconDos4.setForeground(new java.awt.Color(0, 153, 51));
        rSTextFieldIconDos4.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.AC_UNIT);
        rSTextFieldIconDos4.setPlaceholder("INGRESA EL CODIGO DEL PRODUCTO");
        rSTextFieldIconDos4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSTextFieldIconDos4ActionPerformed(evt);
            }
        });
        rSTextFieldIconDos4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rSTextFieldIconDos4KeyReleased(evt);
            }
        });

        rSTextFieldIconDos5.setEditable(false);
        rSTextFieldIconDos5.setForeground(new java.awt.Color(0, 153, 51));
        rSTextFieldIconDos5.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.AC_UNIT);
        rSTextFieldIconDos5.setPlaceholder("INGRESA LA DESCRIPCION DEL PRODUCTO");
        rSTextFieldIconDos5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSTextFieldIconDos5ActionPerformed(evt);
            }
        });

        rSTextFieldIconDos6.setEditable(false);
        rSTextFieldIconDos6.setForeground(new java.awt.Color(0, 153, 51));
        rSTextFieldIconDos6.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.AC_UNIT);
        rSTextFieldIconDos6.setPlaceholder("INGRESA EL PRECIO DEL PRODUCTO");
        rSTextFieldIconDos6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSTextFieldIconDos6ActionPerformed(evt);
            }
        });

        rSTextFieldIconDos7.setForeground(new java.awt.Color(0, 153, 51));
        rSTextFieldIconDos7.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADJUST);
        rSTextFieldIconDos7.setPlaceholder("INGRESA LA CANTIDAD DE VENTA DEL PRODUCTO");
        rSTextFieldIconDos7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSTextFieldIconDos7ActionPerformed(evt);
            }
        });
        rSTextFieldIconDos7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rSTextFieldIconDos7KeyReleased(evt);
            }
        });

        rSButton1.setBackground(new java.awt.Color(0, 153, 102));
        rSButton1.setText("REALIZAR VENTA");
        rSButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton1ActionPerformed(evt);
            }
        });

        rSLabelTextIcon1.setText("TOTAL DEL PRODUCTO");
        rSLabelTextIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EXTENSION);

        rSTableMetro11.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD. PROD", "DESCRIPCION", "PRECIO", "CANT.", "DESC.", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        rSTableMetro11.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                rSTableMetro11ComponentAdded(evt);
            }
        });
        rSTableMetro11.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                rSTableMetro11AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(rSTableMetro11);

        rSButton2.setText("AÑADIR A CARRITO");
        rSButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton2ActionPerformed(evt);
            }
        });

        rSLabelTextIcon2.setText("TOTAL A COBRAR");
        rSLabelTextIcon2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EXTENSION);

        rSButton3.setBackground(new java.awt.Color(255, 51, 51));
        rSButton3.setText("ELIMINAR DEL CARRITO");
        rSButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton3ActionPerformed(evt);
            }
        });

        rSTextFieldIconDos8.setForeground(new java.awt.Color(0, 153, 51));
        rSTextFieldIconDos8.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADJUST);
        rSTextFieldIconDos8.setPlaceholder("INGRESA EL DESCUENTO DEL PRODUCTO");
        rSTextFieldIconDos8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSTextFieldIconDos8ActionPerformed(evt);
            }
        });
        rSTextFieldIconDos8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rSTextFieldIconDos8KeyReleased(evt);
            }
        });

        rSTextFieldIconDos9.setEditable(false);
        rSTextFieldIconDos9.setForeground(new java.awt.Color(0, 153, 51));
        rSTextFieldIconDos9.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.AC_UNIT);
        rSTextFieldIconDos9.setPlaceholder("INGRESA LA CANTIDAD DEL PRODUCTO");
        rSTextFieldIconDos9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSTextFieldIconDos9ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("EL PRECIO DEL PRODUCTO ES:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("LA CANT. DEL PRODCUTO ES:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(rSButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(rSButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rSTextFieldIconDos7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rSTextFieldIconDos5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rSTextFieldIconDos4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rSTextFieldIconDos3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rSTextFieldIconDos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rSTextFieldIconDos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(rSLabelBorderRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rSTextFieldIconDos8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rSTextFieldIconDos9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rSTextFieldIconDos6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rSLabelTextIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rSLabelBorderRound2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(rSButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rSTextFieldIconDos1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rSTextFieldIconDos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rSTextFieldIconDos3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rSTextFieldIconDos4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rSTextFieldIconDos5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rSTextFieldIconDos6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rSTextFieldIconDos9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rSTextFieldIconDos7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rSTextFieldIconDos8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rSLabelBorderRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rSButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rSButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rSLabelBorderRound2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(rSLabelTextIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rSButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSTextFieldIconDos4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSTextFieldIconDos4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSTextFieldIconDos4ActionPerformed

    private void rSTextFieldIconDos5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSTextFieldIconDos5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSTextFieldIconDos5ActionPerformed

    private void rSTextFieldIconDos6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSTextFieldIconDos6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSTextFieldIconDos6ActionPerformed

    private void rSTextFieldIconDos7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSTextFieldIconDos7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSTextFieldIconDos7ActionPerformed

    private void rSTextFieldIconDos1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rSTextFieldIconDos1KeyReleased
        ControllerCliente cli=new ControllerCliente();
        cli.Busqueda_cliente(rSTextFieldIconDos1.getText(), rSTextFieldIconDos2, rSTextFieldIconDos3);
        // TODO add your handling code here:
    }//GEN-LAST:event_rSTextFieldIconDos1KeyReleased

    private void rSTextFieldIconDos4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rSTextFieldIconDos4KeyReleased
        ControllerProducto prod=new ControllerProducto();
        prod.Busqueda_producto(rSTextFieldIconDos4.getText(), rSTextFieldIconDos5, rSTextFieldIconDos6,rSTextFieldIconDos9);        // TODO add your handling code here:
    }//GEN-LAST:event_rSTextFieldIconDos4KeyReleased

    private void rSTextFieldIconDos7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rSTextFieldIconDos7KeyReleased
        rSLabelBorderRound1.setText(Double.toString(Double.parseDouble(rSTextFieldIconDos7.getText())*Double.parseDouble(rSTextFieldIconDos6.getText()))+" Bs.");
                // TODO add your handling code here:
    }//GEN-LAST:event_rSTextFieldIconDos7KeyReleased

    private void rSButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton2ActionPerformed
        
        if(rSTextFieldIconDos8.getText().equals("") || rSTextFieldIconDos8.getText().equals(" "))
        {
            rSTextFieldIconDos8.setText("0");
        }
        DefaultTableModel modelo=(DefaultTableModel)rSTableMetro11.getModel();
        
        modelo.addRow(new Object[]{rSTextFieldIconDos4.getText(),rSTextFieldIconDos5.getText(),rSTextFieldIconDos6.getText(),rSTextFieldIconDos7.getText(),rSTextFieldIconDos8.getText(),Double.toString((Double.parseDouble(rSTextFieldIconDos7.getText())*Double.parseDouble(rSTextFieldIconDos6.getText()))-Double.parseDouble(rSTextFieldIconDos8.getText()))});
        float total=0;
        for(int i=0;i<modelo.getRowCount();i++)
        {
            total+=Double.parseDouble(modelo.getValueAt(i,5).toString());
        }
        BigDecimal bd = new BigDecimal(total).setScale(2, RoundingMode.HALF_UP);
        double val2 = bd.doubleValue();
        rSLabelBorderRound2.setText(Double.toString(val2));
        
        rSTextFieldIconDos7.setText("");
        rSTextFieldIconDos8.setText("");
        
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButton2ActionPerformed

    private void rSButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton3ActionPerformed
        if(rSTableMetro11.getSelectedRow()>=0)
        {
            DefaultTableModel modelo=(DefaultTableModel)rSTableMetro11.getModel();
            modelo.removeRow(rSTableMetro11.getSelectedRow());
            float total=0;
            for(int i=0;i<modelo.getRowCount();i++)
            {
                total+=Double.parseDouble(modelo.getValueAt(i,4).toString());
            }
            BigDecimal bd = new BigDecimal(total).setScale(2, RoundingMode.HALF_UP);
            double val2 = bd.doubleValue();
            rSLabelBorderRound2.setText(Double.toString(val2));
        }
        else
        {
            JOptionPane.showMessageDialog(null, "SELECCIONA UNA FILA POR FAVOR","ADVERTENCIA",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_rSButton3ActionPerformed

    private void rSTableMetro11ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_rSTableMetro11ComponentAdded
              // TODO add your handling code here:
    }//GEN-LAST:event_rSTableMetro11ComponentAdded

    private void rSTableMetro11AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_rSTableMetro11AncestorAdded
         // TODO add your handling code here:
    }//GEN-LAST:event_rSTableMetro11AncestorAdded

    private void rSButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton1ActionPerformed
        if(JOptionPane.showConfirmDialog(null,"¿ESTAS SEGUR@ DE REALIZAR LA VENTA?","ALERTA",JOptionPane.YES_NO_OPTION)==0)
        {
            ControllerVentas venta=new ControllerVentas();
            venta.Vender_Producto(rSTableMetro11, rSTextFieldIconDos1.getText(),usuario,contrasena,rSTextFieldIconDos1.getText(),rSTextFieldIconDos2.getText(),rSTextFieldIconDos3.getText());
            venta.Mostrar_Ventas_Emp(tabla);
            this.setVisible(false);
            
        }
    }//GEN-LAST:event_rSButton1ActionPerformed

    private void rSTextFieldIconDos8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSTextFieldIconDos8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSTextFieldIconDos8ActionPerformed

    private void rSTextFieldIconDos8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rSTextFieldIconDos8KeyReleased
        rSLabelBorderRound1.setText(Double.toString(Double.parseDouble(rSTextFieldIconDos7.getText())*Double.parseDouble(rSTextFieldIconDos6.getText())-(Double.parseDouble(rSTextFieldIconDos8.getText()))) +" Bs.");                // TODO add your handling code here:
    }//GEN-LAST:event_rSTextFieldIconDos8KeyReleased

    private void rSTextFieldIconDos9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSTextFieldIconDos9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSTextFieldIconDos9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private rojeru_san.RSButton rSButton1;
    private rojeru_san.RSButton rSButton2;
    private rojeru_san.RSButton rSButton3;
    private rojeru_san.rslabel.RSLabelBorderRound rSLabelBorderRound1;
    private rojeru_san.rslabel.RSLabelBorderRound rSLabelBorderRound2;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon1;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon2;
    private rojerusan.RSTableMetro1 rSTableMetro11;
    private RSMaterialComponent.RSTextFieldIconDos rSTextFieldIconDos1;
    private RSMaterialComponent.RSTextFieldIconDos rSTextFieldIconDos2;
    private RSMaterialComponent.RSTextFieldIconDos rSTextFieldIconDos3;
    private RSMaterialComponent.RSTextFieldIconDos rSTextFieldIconDos4;
    private RSMaterialComponent.RSTextFieldIconDos rSTextFieldIconDos5;
    private RSMaterialComponent.RSTextFieldIconDos rSTextFieldIconDos6;
    private RSMaterialComponent.RSTextFieldIconDos rSTextFieldIconDos7;
    private RSMaterialComponent.RSTextFieldIconDos rSTextFieldIconDos8;
    private RSMaterialComponent.RSTextFieldIconDos rSTextFieldIconDos9;
    // End of variables declaration//GEN-END:variables
}
