/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.EMPLEADO;

import controller.ControllerVentas;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author hdani
 */
public class VENTAS extends javax.swing.JInternalFrame {

    /**
     * Creates new form VENTAS
     */
    JDesktopPane panel=null;
    public String usuario="",contrasena="";
    public VENTAS(JDesktopPane panel,String us, String con) {
        initComponents();
        this.panel=panel;
        this.usuario=us;
        this.contrasena=con;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        rSTableMetro1 = new RSMaterialComponent.RSTableMetro();
        rSButtonIconUno4 = new RSMaterialComponent.RSButtonIconUno();
        rSButtonIconUno5 = new RSMaterialComponent.RSButtonIconUno();
        rSMetroTextFullPlaceHolder1 = new rojerusan.RSMetroTextFullPlaceHolder();
        rSButtonCustomIcon1 = new RSMaterialComponent.RSButtonCustomIcon();
        rSButtonForma1 = new rojeru_san.rsbutton.RSButtonForma();
        rSButtonForma2 = new rojeru_san.rsbutton.RSButtonForma();
        rSButtonForma3 = new rojeru_san.rsbutton.RSButtonForma();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        rSTableMetro1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(rSTableMetro1);

        rSButtonIconUno4.setBackground(new java.awt.Color(102, 153, 0));
        rSButtonIconUno4.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.NAVIGATE_BEFORE);
        rSButtonIconUno4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconUno4ActionPerformed(evt);
            }
        });

        rSButtonIconUno5.setBackground(new java.awt.Color(102, 153, 0));
        rSButtonIconUno5.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.NAVIGATE_NEXT);
        rSButtonIconUno5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconUno5ActionPerformed(evt);
            }
        });

        rSMetroTextFullPlaceHolder1.setPlaceholder("INGRESA EL CI DEL CLIENTE");
        rSMetroTextFullPlaceHolder1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rSMetroTextFullPlaceHolder1KeyReleased(evt);
            }
        });

        rSButtonCustomIcon1.setText("GENERAR PROFORMA");
        rSButtonCustomIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FILE_DOWNLOAD);
        rSButtonCustomIcon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonCustomIcon1ActionPerformed(evt);
            }
        });

        rSButtonForma1.setBackground(new java.awt.Color(255, 51, 51));
        rSButtonForma1.setText("ELIMINAR VENTA");
        rSButtonForma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonForma1ActionPerformed(evt);
            }
        });

        rSButtonForma2.setBackground(new java.awt.Color(0, 153, 51));
        rSButtonForma2.setText("REALIZAR VENTA");
        rSButtonForma2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonForma2ActionPerformed(evt);
            }
        });

        rSButtonForma3.setBackground(new java.awt.Color(255, 153, 0));
        rSButtonForma3.setText("EDITAR VENTA");
        rSButtonForma3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonForma3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1319, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(rSButtonForma2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rSButtonForma3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rSMetroTextFullPlaceHolder1, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rSButtonCustomIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rSButtonIconUno4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rSButtonIconUno5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rSButtonForma1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rSButtonCustomIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rSMetroTextFullPlaceHolder1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rSButtonIconUno4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rSButtonIconUno5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSButtonForma3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonForma1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonForma2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonIconUno4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconUno4ActionPerformed
        int ultima_fila=rSTableMetro1.getSelectedRow();
        ultima_fila-=1;
        if(ultima_fila<0)
        {
            ultima_fila=rSTableMetro1.getRowCount()-1;
        }
        rSTableMetro1.setRowSelectionInterval(ultima_fila,ultima_fila);
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonIconUno4ActionPerformed

    private void rSButtonIconUno5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconUno5ActionPerformed
        int ultima_fila=rSTableMetro1.getSelectedRow();
        ultima_fila+=1;
        if(ultima_fila==rSTableMetro1.getRowCount())
        {
            rSTableMetro1.setRowSelectionInterval(0, 0);
        }
        else
        {
            rSTableMetro1.setRowSelectionInterval(ultima_fila,ultima_fila);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonIconUno5ActionPerformed

    private void rSMetroTextFullPlaceHolder1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rSMetroTextFullPlaceHolder1KeyReleased
        ControllerVentas ventas=new ControllerVentas();
        ventas.Mostrar_Ventas_Emp_Ci(rSTableMetro1, rSMetroTextFullPlaceHolder1.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMetroTextFullPlaceHolder1KeyReleased

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        ControllerVentas ventas=new ControllerVentas();
        ventas.Mostrar_Ventas_Emp(rSTableMetro1);
        TableColumnModel columnModel = rSTableMetro1.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(100);
        columnModel.getColumn(1).setPreferredWidth(500);
        columnModel.getColumn(2).setPreferredWidth(100);
        columnModel.getColumn(3).setPreferredWidth(100);
        columnModel.getColumn(4).setPreferredWidth(100);
        columnModel.getColumn(5).setPreferredWidth(100);
        columnModel.getColumn(6).setPreferredWidth(100);
        columnModel.getColumn(7).setPreferredWidth(100);
        columnModel.getColumn(8).setPreferredWidth(100);
        columnModel.getColumn(9).setPreferredWidth(100);
// TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameActivated

    private void rSButtonForma2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonForma2ActionPerformed
        REALIZAR_VENTA venta=new REALIZAR_VENTA(panel,usuario,contrasena,rSTableMetro1);
        panel.add(venta);
        venta.setLocation(10, 10);
        venta.setVisible(true);
        panel.repaint();
        panel.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonForma2ActionPerformed

    private void rSButtonForma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonForma1ActionPerformed
        if(JOptionPane.showConfirmDialog(null,"¿ESTAS SEGUR@ DE REALIZAR LA ELIMINACION DE LA VENTA?","ALERTA",JOptionPane.YES_NO_OPTION)==0)
        {
            if(rSTableMetro1.getSelectedRow()>=0)
            {
                ControllerVentas venta=new ControllerVentas();
                venta.Eliminar_Producto(rSTableMetro1.getModel().getValueAt(rSTableMetro1.getSelectedRow(),0).toString(),rSTableMetro1.getModel().getValueAt(rSTableMetro1.getSelectedRow(),3).toString(),rSTableMetro1.getModel().getValueAt(rSTableMetro1.getSelectedRow(),6).toString(),rSTableMetro1.getModel().getValueAt(rSTableMetro1.getSelectedRow(),8).toString(),rSTableMetro1.getModel().getValueAt(rSTableMetro1.getSelectedRow(),9).toString());
                venta.Mostrar_Ventas_Emp(rSTableMetro1);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "PORFAVOR SELECCIONA UNA FILA");
            }
        }                // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonForma1ActionPerformed

    private void rSButtonCustomIcon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonCustomIcon1ActionPerformed
        if(rSTableMetro1.getSelectedRow()>=0)
        {
            ControllerVentas ventas=new ControllerVentas();
            ventas.ImprimirPDF(Integer.parseInt(rSTableMetro1.getModel().getValueAt(rSTableMetro1.getSelectedRow(),9).toString()));
        }
        else
        {
            JOptionPane.showMessageDialog(null, "PORFAVOR SELECCIONA UNA FILA");
        }
    }//GEN-LAST:event_rSButtonCustomIcon1ActionPerformed

    private void rSButtonForma3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonForma3ActionPerformed
        if(rSTableMetro1.getSelectedRow()>=0)
        {
            if(JOptionPane.showConfirmDialog(null,"RECUERDA QUE SOLO PUEDES EDITAR LA CANTIDAD DE VENTA","ALERTA",JOptionPane.YES_NO_OPTION)==0)
            {
                String f=JOptionPane.showInputDialog(null, "INGRESA LA NUEVA CANTIDAD DE LA VENTA");
                if(!f.isEmpty() || Integer.parseInt(f)>0)
                {
                    ControllerVentas venta=new ControllerVentas();
                    venta.Editar_Producto(rSTableMetro1.getModel().getValueAt(rSTableMetro1.getSelectedRow(),0).toString(),f,rSTableMetro1.getModel().getValueAt(rSTableMetro1.getSelectedRow(),6).toString(),rSTableMetro1.getModel().getValueAt(rSTableMetro1.getSelectedRow(),8).toString(),rSTableMetro1.getModel().getValueAt(rSTableMetro1.getSelectedRow(),9).toString());
                    venta.Mostrar_Ventas_Emp(rSTableMetro1);
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "PORFAVOR INGRESA UN DATO VALIDO");
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "PORFAVOR SELECCIONA UNA FILA");
        }// TODO add your handling code here:
    }//GEN-LAST:event_rSButtonForma3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private RSMaterialComponent.RSButtonCustomIcon rSButtonCustomIcon1;
    private rojeru_san.rsbutton.RSButtonForma rSButtonForma1;
    private rojeru_san.rsbutton.RSButtonForma rSButtonForma2;
    private rojeru_san.rsbutton.RSButtonForma rSButtonForma3;
    private RSMaterialComponent.RSButtonIconUno rSButtonIconUno4;
    private RSMaterialComponent.RSButtonIconUno rSButtonIconUno5;
    private rojerusan.RSMetroTextFullPlaceHolder rSMetroTextFullPlaceHolder1;
    private RSMaterialComponent.RSTableMetro rSTableMetro1;
    // End of variables declaration//GEN-END:variables
}
